services:
  xyops:
    build: .
    container_name: xyops
    hostname: xyops
    restart: unless-stopped
    ports:
      - "5522:5522"
      - "5523:5523"
    environment:
      - XYOPS_foreground=true
      - XYOPS_color=true
      - XYOPS_masters=xyops
      - XYOPS_xysat_local=true
      # NODE_MAX_MEMORY: 4096
    volumes:
      - /opt/xyops/data:/opt/xyops/data
      - /opt/xyops/conf:/opt/xyops/conf
      - /opt/xyops/logs:/opt/xyops/logs
